version: '3'
services:
  server:
    build:
      context: server
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    networks:
      - server-tier
      - client-tier
  client:
    build:
      context: client
      dockerfile: Dockerfile
    ports:
      - "5003:5003"
    networks:
      - client-tier
      - server-tier

networks:
  server-tier:
  client-tier:
# version: '3'
# services:
#   server:
#     build: ./server
#     container_name: server
#     ports:
#       - 8082:8082
#   client:
#     build: ./client
#     container_name: client
#     ports:
#       - 81:81